# Generated by Django 3.2.5 on 2022-07-18 06:57

import base.models.functions
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomGuest',
            fields=[
                ('id', models.CharField(default=base.models.functions.create_id, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('is_allowed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.room')),
            ],
        ),
        migrations.AddConstraint(
            model_name='roomguest',
            constraint=models.UniqueConstraint(fields=('room', 'guest'), name='unique_stock'),
        ),
    ]
